### ISSUE TITLE
Petition to rename to "mov-cli-jellyplex"

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli-jellyplex#4]
What do you think about a rename to something like "jellyplex".

> 🪼🐬 Jellyfin + 📺 Plex

<img width="20px" src="https://media.tenor.com/67qTcyIjsm4AAAAi/anime-tonikaku-kawaii.gif">

**Comment by ananasmoe** [comment]
<img width="50" src="https://github.com/mov-cli/mov-cli-media-server/assets/132799819/1d48d21f-8803-4e09-b74b-0fcefe688c88">
